# Use a imagem base desejada
FROM <imagem_base>

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie os arquivos do host para o contêiner
COPY . .

# Execute os comandos de instalação e configuração necessários
RUN <comandos_de_instalação>

# Exponha a porta necessária para o aplicativo
EXPOSE <porta>

# Defina o comando de inicialização do aplicativo
CMD [ "comando_de_inicialização" ]
